### PR TITLE
make sure to add header with files module url if there is directories…

### PR DESCRIPTION
**Pull request by mostafahussein**
I have found a workaround to solve this #15 but please note that you may need more condition in order to avoid such issues like if you have `%script` for example which use `cmd.script` module and not `cmd.run`, do you have another idea that could solve it in a better way ?

### CODE REVIEW

**Comment by mostafahussein** [comment]
@openx-luis could you review this one too ?

**Comment by mostafahussein** [comment]
I thought i need to update the base in case it will be merged but the changes now not showing correctly

**Comment by openx-luis** [comment]
Can you rebase against current master?

**Comment by mostafahussein** [comment]
updated

**Comment by openx-luis** [comment]
Ok, I see what you're trying to do, but it's a bit ugly. Can I suggest a different approach?

```
    def has_sections(self, *names):
        return any(self.has_section(name) for name in names)
```

```
    def section_files_header(self):
        """
        Generate the section header for the files section.
        """
        lines = []
        name = 'files'
        if self.has_sections('files', 'directories'):
            lines.append(TEMPLATES['module_header'].render(module=name.upper(), doc_link=DOC_URLS[name]))
        return '\n'.join(lines)
```

```
    def generate_sls(self):
        sections = [
            ...,
            self.section_files_header(),
            ...,
        ]
        return '\n'.join(sec for sec in sections if sec)
```

**Comment by openx-luis** [comment]
This will avoid overcomplicating the simple `has_section()` method. Feel free to open a new PR if you get a chance :)

**Comment by druonysus** [comment]
@openx-luis and @mostafahussein I merged this because it looks to address the issue for now... I do think this needs to be fixed in a more maintainable way.

**Comment by mostafahussein** [comment]
Fine I will update the code as you suggested, and yes it looks better than what i added also it will be easily to extend if there are more salt modules that needs to be supported like `cmd.script`.

**Comment by openx-luis** [comment]
Exactly. I'm thinking maybe we can add the above `has_sections` method and rewrite `section_header` to account for the fact that it might depend on other sections:

```
    def section_header(self, name, extra=None):
        """
        Generate the section header for the named section.
        """
        lines = []
        if self.has_section(name) or self.has_sections(*extra):
            lines.append(TEMPLATES['module_header'].render(module=name.upper(), doc_link=DOC_URLS[name]))
        return '\n'.join(lines)
```

Then in `generate_sls` we just call `self.section_header('files', extra=['directories'])`

Just brainstorming, though. What do you think?

**Pull request merged**
